# Generated by Django 4.0.1 on 2022-01-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('full_name', models.CharField(max_length=50, verbose_name='nombres')),
                ('pasaporte', models.CharField(max_length=50, verbose_name='Pasaporte')),
                ('apelativo', models.CharField(max_length=50, verbose_name='Apelativo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.persona')),
                ('empleo', models.CharField(max_length=50, verbose_name='Empleo')),
            ],
            bases=('home.persona',),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18)), name='mayor_edad_18'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('pais', 'apelativo')},
        ),
    ]
