# Generated by Django 3.2.9 on 2022-01-19 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lector', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
        ),
    ]
